<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="quyentx-w7" name="com.vsii.tsc.guru.testcase.WebService" tests="5" failures="0" timestamp="29 Mar 2016 03:33:10 GMT" time="47.437" errors="1">
  <testcase name="W07" time="0.000" classname="com.vsii.tsc.guru.testcase.WebService">
    <error type="org.testng.TestNGException" message="
Method public void com.vsii.tsc.guru.testcase.WebService.W07(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : W07 in class com.vsii.tsc.guru.testdata.TestData">
      <![CDATA[org.testng.TestNGException: 
Method public void com.vsii.tsc.guru.testcase.WebService.W07(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : W07 in class com.vsii.tsc.guru.testdata.TestData
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </error>
  </testcase> <!-- W07 -->
  <testcase name="W01" time="27.985" classname="com.vsii.tsc.guru.testcase.WebService"/>
  <testcase name="W04" time="8.074" classname="com.vsii.tsc.guru.testcase.WebService"/>
  <testcase name="W03" time="6.086" classname="com.vsii.tsc.guru.testcase.WebService"/>
  <testcase name="W02" time="5.292" classname="com.vsii.tsc.guru.testcase.WebService"/>
</testsuite> <!-- com.vsii.tsc.guru.testcase.WebService -->
